[package]
name = "api"
version.workspace = true
edition.workspace = true

[dependencies]
actix-web.workspace = true
actix-multipart = "0.6"
actix-cors = "0.6"
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
tokio.workspace = true
futures-util = "0.3"
orderbook = { path = "../orderbook" }
matching = { path = "../matching" }
engine = { path = "../engine" }
