using UnityEngine;
using System.Text;
using System.Collections.Generic;
using System.IO;
using CircuitSimulator.Components;

namespace CircuitSimulator.Core
{
    public class SpiceExporter : MonoBehaviour
    {
        public static SpiceExporter Instance { get; private set; }

        private int nodeCounter;
        private Dictionary<CircuitNode, string> nodeToSpiceName = new Dictionary<CircuitNode, string>();

        private void Awake()
        {
            if (Instance == null)
            {
                Instance = this;
            }
            else
            {
                Destroy(gameObject);
            }
        }

        public string ExportToSpiceNetlist(string circuitName = "Circuit")
        {
            StringBuilder sb = new StringBuilder();
            nodeCounter = 0;
            nodeToSpiceName.Clear();

            sb.AppendLine($"* SPICE Netlist: {circuitName}");
            sb.AppendLine($"* Generated by Circuit Simulator");
            sb.AppendLine($"* Date: {System.DateTime.Now}");
            sb.AppendLine();

            var elements = CircuitSimulator.Instance.GetAllElements();
            var allNodes = new List<CircuitNode>();

            foreach (var element in elements)
            {
                foreach (var node in element.Nodes)
                {
                    if (!allNodes.Contains(node))
                        allNodes.Add(node);
                }
            }

            foreach (var node in allNodes)
            {
                if (node.IsGround)
                {
                    nodeToSpiceName[node] = "0";
                }
                else
                {
                    nodeCounter++;
                    nodeToSpiceName[node] = $"N{nodeCounter}";
                }
            }

            sb.AppendLine("* --- Nodes ---");
            foreach (var kvp in nodeToSpiceName)
            {
                string type = kvp.Key.IsGround ? " (Ground)" : "";
                sb.AppendLine($"* Node {kvp.Value} at ({kvp.Key.Position.x:F2}, {kvp.Key.Position.y:F2}){type}");
            }
            sb.AppendLine();

            sb.AppendLine("* --- Circuit Elements ---");

            int elementIndex = 1;
            foreach (var element in elements)
            {
                string spiceLine = ConvertElementToSpice(element, ref elementIndex);
                if (!string.IsNullOrEmpty(spiceLine))
                {
                    sb.AppendLine(spiceLine);
                }
            }

            sb.AppendLine();
            sb.AppendLine("* --- Analysis Commands ---");
            sb.AppendLine(".OP");
            sb.AppendLine(".TRAN 1e-4 10e-3");
            sb.AppendLine(".END");

            return sb.ToString();
        }

        private string ConvertElementToSpice(CircuitElement element, ref int index)
        {
            if (element.Nodes.Count < 2)
                return $"* Warning: Element {element.GetType().Name} has insufficient nodes";

            switch (element)
            {
                case VoltageSource vs:
                    return ExportVoltageSource(vs, ref index);
                case ACVoltageSource ac:
                    return ExportACVoltageSource(ac, ref index);
                case Resistor r:
                    return ExportResistor(r, ref index);
                case Capacitor c:
                    return ExportCapacitor(c, ref index);
                case Inductor l:
                    return ExportInductor(l, ref index);
                case Diode d:
                    return ExportDiode(d, ref index);
                case Wire w:
                    return ExportWire(w, ref index);
                default:
                    return $"* Unsupported element: {element.GetType().Name}";
            }
        }

        private string ExportVoltageSource(VoltageSource vs, ref int index)
        {
            if (vs.Nodes.Count < 2) return null;

            string posNode = GetSpiceNode(vs.Nodes[0]);
            string negNode = GetSpiceNode(vs.Nodes[1]);
            float voltage = 0;
            var param = vs.GetParameters();
            if (param.TryGetValue("Voltage", out var v)) voltage = v;

            string line = $"V{index} {posNode} {negNode} DC {voltage:F3}";
            
            if (vs.HasFault)
            {
                line += $" * FAULT: {vs.CurrentFault}";
            }
            
            index++;
            return line;
        }

        private string ExportACVoltageSource(ACVoltageSource ac, ref int index)
        {
            if (ac.Nodes.Count < 2) return null;

            string posNode = GetSpiceNode(ac.Nodes[0]);
            string negNode = GetSpiceNode(ac.Nodes[1]);
            
            var param = ac.GetParameters();
            float amplitude = param.TryGetValue("Amplitude", out var a) ? a : 5f;
            float frequency = param.TryGetValue("Frequency", out var f) ? f : 50f;
            float phase = param.TryGetValue("Phase", out var p) ? p : 0f;

            string line = $"V{index} {posNode} {negNode} AC {amplitude:F3} SIN(0 {amplitude:F3} {frequency:F1} 0 0 {phase:F3})";
            
            if (ac.HasFault)
            {
                line += $" * FAULT: {ac.CurrentFault}";
            }
            
            index++;
            return line;
        }

        private string ExportResistor(Resistor r, ref int index)
        {
            if (r.Nodes.Count < 2) return null;

            string node1 = GetSpiceNode(r.Nodes[0]);
            string node2 = GetSpiceNode(r.Nodes[1]);
            float resistance = 100;
            var param = r.GetParameters();
            if (param.TryGetValue("Resistance", out var val)) resistance = val;

            string line = $"R{index} {node1} {node2} {resistance:F3}";
            
            if (r.HasFault)
            {
                line += $" * FAULT: {r.CurrentFault}";
            }
            
            index++;
            return line;
        }

        private string ExportCapacitor(Capacitor c, ref int index)
        {
            if (c.Nodes.Count < 2) return null;

            string node1 = GetSpiceNode(c.Nodes[0]);
            string node2 = GetSpiceNode(c.Nodes[1]);
            float capacitance = 0.001f;
            var param = c.GetParameters();
            if (param.TryGetValue("Capacitance", out var val)) capacitance = val;

            string line = $"C{index} {node1} {node2} {capacitance:F6} IC=0";
            
            if (c.HasFault)
            {
                line += $" * FAULT: {c.CurrentFault}";
            }
            
            index++;
            return line;
        }

        private string ExportInductor(Inductor l, ref int index)
        {
            if (l.Nodes.Count < 2) return null;

            string node1 = GetSpiceNode(l.Nodes[0]);
            string node2 = GetSpiceNode(l.Nodes[1]);
            float inductance = 0.01f;
            var param = l.GetParameters();
            if (param.TryGetValue("Inductance", out var val)) inductance = val;

            string line = $"L{index} {node1} {node2} {inductance:F6} IC=0";
            
            if (l.HasFault)
            {
                line += $" * FAULT: {l.CurrentFault}";
            }
            
            index++;
            return line;
        }

        private string ExportDiode(Diode d, ref int index)
        {
            if (d.Nodes.Count < 2) return null;

            string anode = GetSpiceNode(d.Nodes[0]);
            string cathode = GetSpiceNode(d.Nodes[1]);

            string line = $"D{index} {anode} {cathode} D_MODEL";
            string modelLine = $".MODEL D_MODEL D (IS=1e-14 N=1.75 RS=0.01)";
            
            if (d.HasFault)
            {
                line += $" * FAULT: {d.CurrentFault}";
            }
            
            index++;
            return line + "\n" + modelLine;
        }

        private string ExportWire(Wire w, ref int index)
        {
            if (w.Nodes.Count < 2) return null;

            string node1 = GetSpiceNode(w.Nodes[0]);
            string node2 = GetSpiceNode(w.Nodes[1]);
            float resistance = 0.001f;
            var param = w.GetParameters();
            if (param.TryGetValue("Resistance", out var val)) resistance = val;

            string line = $"RW{index} {node1} {node2} {resistance:F6}";
            index++;
            return line;
        }

        private string GetSpiceNode(CircuitNode node)
        {
            if (nodeToSpiceName.TryGetValue(node, out string name))
                return name;
            return "?";
        }

        public void SaveNetlistToFile(string filePath, string circuitName = "Circuit")
        {
            string netlist = ExportToSpiceNetlist(circuitName);
            File.WriteAllText(filePath, netlist);
            Debug.Log($"SPICE netlist saved to: {filePath}");
        }

        public string GetSpiceNetlistPreview()
        {
            string netlist = ExportToSpiceNetlist("Preview");
            string[] lines = netlist.Split('\n');
            int previewLines = Mathf.Min(20, lines.Length);
            StringBuilder preview = new StringBuilder();
            for (int i = 0; i < previewLines; i++)
            {
                preview.AppendLine(lines[i]);
            }
            if (lines.Length > previewLines)
            {
                preview.AppendLine($"... ({lines.Length - previewLines} more lines)");
            }
            return preview.ToString();
        }
    }
}
