use crate::report::{ConversionReport, Incompatibility};
use crate::type_mapping::{build_type_mappings, extract_type_with_params, map_type};
use regex::Regex;

pub struct DDLConverter {
    type_mappings: std::collections::HashMap<String, crate::type_mapping::TypeMapping>,
}

impl DDLConverter {
    pub fn new() -> Self {
        Self {
            type_mappings: build_type_mappings(),
        }
    }

    pub fn convert_create_table(&self, sql: &str, report: &mut ConversionReport) -> String {
        let mut result = sql.to_string();

        result = self.convert_identity_columns(&result, report);
        result = self.convert_data_types(&result, report);
        result = self.convert_constraints(&result, report);
        result = self.convert_table_options(&result, report);

        result
    }

    fn convert_identity_columns(&self, sql: &str, report: &mut ConversionReport) -> String {
        let re = Regex::new(r"(?i)(\w+)\s+(\w+(?:\s*\([^)]+\))?)\s+.*?(GENERATED\s+(?:ALWAYS|BY\s+DEFAULT)\s+AS\s+IDENTITY[^,\n]*)").unwrap();
        let mut result = sql.to_string();

        for caps in re.captures_iter(sql) {
            let col_name = &caps[1];
            let col_type = &caps[2];
            let identity_clause = &caps[3];

            let (base_type, _params) = extract_type_with_params(col_type);
            let pg_serial_type = match base_type.as_str() {
                "SMALLINT" => "SMALLSERIAL",
                "INTEGER" | "INT" => "SERIAL",
                "BIGINT" => "BIGSERIAL",
                _ => "SERIAL",
            };

            let original = format!("{} {} {}", col_name, col_type, identity_clause);
            let converted = format!("{} {}", col_name, pg_serial_type);

            result = result.replace(&original, &converted);

            report.add_incompatibility(
                Incompatibility::info(
                    0,
                    "IDENTITY",
                    &original,
                    "DB2 IDENTITY column converted to PostgreSQL SERIAL type"
                )
                .with_converted(&converted)
                .with_suggestion("PostgreSQL SERIAL auto-creates a sequence for auto-incrementing")
            );
        }

        result
    }

    fn convert_data_types(&self, sql: &str, report: &mut ConversionReport) -> String {
        let re = Regex::new(r"(?i)(\w+)\s+([A-Za-z]+(?:\s*\([^)]+\))?)").unwrap();
        let mut result = sql.to_string();

        for caps in re.captures_iter(sql) {
            let col_name = &caps[1];
            let full_type = &caps[2];
            
            let (base_type, params) = extract_type_with_params(full_type);
            let mapping = map_type(&base_type, &self.type_mappings);
            
            let pg_type = if let Some(p) = params {
                format!("{}({})", mapping.pg_type(), p)
            } else {
                mapping.pg_type().to_string()
            };

            if mapping.pg_type() != base_type {
                let original = format!("{} {}", col_name, full_type);
                let converted = format!("{} {}", col_name, pg_type);
                result = result.replace(&original, &converted);

                report.add_type_mapping(&full_type, &pg_type);

                if let Some(note) = mapping.note() {
                    report.add_incompatibility(
                        Incompatibility::info(
                            0,
                            "Type Mapping",
                            &original,
                            note
                        )
                        .with_converted(&converted)
                    );
                }
            }
        }

        result
    }

    fn convert_constraints(&self, sql: &str, _report: &mut ConversionReport) -> String {
        let mut result = sql.to_string();

        result = result.replace("GENERATED BY DEFAULT", "");
        result = result.replace("GENERATED ALWAYS", "");

        result
    }

    fn convert_table_options(&self, sql: &str, report: &mut ConversionReport) -> String {
        let mut result = sql.to_string();

        if result.contains("ORGANIZE BY") {
            report.add_incompatibility(
                Incompatibility::medium(
                    0,
                    "Table Option",
                    "ORGANIZE BY",
                    "DB2 ORGANIZE BY clause has no direct equivalent in PostgreSQL"
                )
                .with_suggestion("Consider using appropriate indexes for similar performance")
            );
            result = Regex::new(r"(?i)\s*ORGANIZE\s+BY\s+[^)]+\)").unwrap()
                .replace_all(&result, "")
                .to_string();
        }

        if result.contains("COMPRESS YES") {
            report.add_incompatibility(
                Incompatibility::info(
                    0,
                    "Table Option",
                    "COMPRESS YES",
                    "DB2 COMPRESS clause converted to PostgreSQL WITH (compression)"
                )
            );
            result = result.replace("COMPRESS YES", "WITH (compression = on)");
        }

        result
    }

    pub fn convert_create_index(&self, sql: &str, report: &mut ConversionReport) -> String {
        let mut result = sql.to_string();

        if result.contains("CLUSTER") {
            report.add_incompatibility(
                Incompatibility::medium(
                    0,
                    "Index Option",
                    "CLUSTER",
                    "DB2 CLUSTER index concept differs from PostgreSQL CLUSTER"
                )
                .with_suggestion("PostgreSQL uses CLUSTER command to physically reorder table")
            );
            result = result.replace("CLUSTER", "");
        }

        result
    }

    pub fn convert_create_sequence(&self, sql: &str, _report: &mut ConversionReport) -> String {
        let mut result = sql.to_string();

        result = result.replace("AS INTEGER", "AS INT4");
        result = result.replace("AS BIGINT", "AS INT8");
        result = result.replace("AS SMALLINT", "AS INT2");

        result
    }

    pub fn convert_create_trigger(&self, sql: &str, report: &mut ConversionReport) -> String {
        let mut result = sql.to_string();

        let re_ref = Regex::new(r"(?i)REFERENCING\s+(.+?)\s+FOR\s+(?:EACH\s+)?(ROW|STATEMENT)").unwrap();
        let mut old_alias = "OLD".to_string();
        let mut new_alias = "NEW".to_string();

        if let Some(caps) = re_ref.captures(sql) {
            let original_ref = caps[0].to_string();
            let ref_content = &caps[1];

            let old_re = Regex::new(r"(?i)OLD\s+AS\s+(\w+)").unwrap();
            let new_re = Regex::new(r"(?i)NEW\s+AS\s+(\w+)").unwrap();

            if let Some(old_caps) = old_re.captures(ref_content) {
                old_alias = old_caps[1].to_string();
            }
            if let Some(new_caps) = new_re.captures(ref_content) {
                new_alias = new_caps[1].to_string();
            }

            result = result.replace(&original_ref, &format!("FOR EACH {}", &caps[2]));

            result = result.replace(&format!("{}.", old_alias), "OLD.");
            result = result.replace(&format!("{}.", new_alias), "NEW.");
        }

        result = result.replace("MODE DB2SQL", "");
        result = result.replace("NO BEFORE", "BEFORE");
        result = result.replace("NO AFTER", "AFTER");

        if result.contains("BEGIN") && result.contains("END") {
            let func_name = if let Some(caps) = Regex::new(r"(?i)CREATE\s+(?:OR\s+REPLACE\s+)?TRIGGER\s+(\w+)").unwrap().captures(sql) {
                format!("{}_func", &caps[1])
            } else {
                "trigger_func".to_string()
            };

            if let Some(body_caps) = Regex::new(r"(?is)BEGIN(.+?)END(?:\s*@)?").unwrap().captures(&result) {
                let original_body = body_caps[0].to_string();
                let body_content = &body_caps[1];

                let processed_body = body_content
                    .replace("SIGNAL SQLSTATE", "RAISE EXCEPTION")
                    .replace("SET MESSAGE_TEXT =", "USING MESSAGE =");

                let func_def = format!(
                    "EXECUTE FUNCTION {}();\n\nCREATE OR REPLACE FUNCTION {}()\nRETURNS TRIGGER AS $$\nBEGIN\n{}\n    RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql;",
                    func_name, func_name, processed_body
                );

                result = result.replace(&original_body, &func_def);
            }
        }

        if sql.contains("REFERENCING") {
            report.add_incompatibility(
                Incompatibility::high(
                    0,
                    "Trigger REFERENCING Clause",
                    &sql[..std::cmp::min(100, sql.len())],
                    "DB2 REFERENCING OLD/NEW AS clause removed - PostgreSQL uses OLD/NEW directly"
                )
                .with_suggestion(format!("Aliases automatically replaced: {} -> OLD, {} -> NEW", old_alias, new_alias).as_str())
            );
        }

        result
    }
}
