apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: iot-data
    jsonData:
      version: Flux
      organization: iot-org
      defaultBucket: iot-data
    secureJsonData:
      token: my-token
