const ParameterAlert = require('../models/production/ParameterAlert');
const ProductionRecord = require('../models/production/ProductionRecord');
const ProcessTemplate = require('../models/process/ProcessTemplate');
const { retryOperation } = require('../config/databases');
const logger = require('../config/logger');

const detectParameterAnomalies = async (productionRecordId, stepIndex, parameters) => {
  const anomalies = [];

  try {
    const record = await ProductionRecord.findById(productionRecordId);
    if (!record) return anomalies;

    const template = await ProcessTemplate.findById(record.processTemplateId);
    if (!template) return anomalies;

    const stepTemplate = template.steps[stepIndex];
    if (!stepTemplate || !stepTemplate.parameters) return anomalies;

    for (const param of parameters) {
      const templateParam = stepTemplate.parameters.find(
        tp => tp.name === param.paramName || tp.name === param.name
      );

      if (!templateParam) {
        continue;
      }

      const paramValue = typeof param.paramValue === 'string'
        ? parseFloat(param.paramValue)
        : param.paramValue;

      if (isNaN(paramValue)) {
        continue;
      }

      const { minValue, maxValue } = templateParam;

      if (minValue !== undefined && paramValue < minValue) {
        const deviation = minValue - paramValue;
        const deviationPercent = ((deviation / minValue) * 100).toFixed(2);

        anomalies.push({
          parameterName: param.paramName || param.name,
          parameterValue: paramValue,
          expectedValue: `>= ${minValue}`,
          minValue,
          maxValue,
          unit: templateParam.unit,
          alertType: 'threshold_exceeded',
          severity: deviationPercent > 20 ? 'high' : deviationPercent > 10 ? 'medium' : 'low',
          deviation,
          deviationPercent: parseFloat(deviationPercent),
          description: `参数 ${param.paramName || param.name} 低于最小值 ${minValue}${templateParam.unit || ''}`
        });
      }

      if (maxValue !== undefined && paramValue > maxValue) {
        const deviation = paramValue - maxValue;
        const deviationPercent = ((deviation / maxValue) * 100).toFixed(2);

        anomalies.push({
          parameterName: param.paramName || param.name,
          parameterValue: paramValue,
          expectedValue: `<= ${maxValue}`,
          minValue,
          maxValue,
          unit: templateParam.unit,
          alertType: 'threshold_exceeded',
          severity: deviationPercent > 20 ? 'high' : deviationPercent > 10 ? 'medium' : 'low',
          deviation,
          deviationPercent: parseFloat(deviationPercent),
          description: `参数 ${param.paramName || param.name} 超过最大值 ${maxValue}${templateParam.unit || ''}`
        });
      }
    }
  } catch (error) {
    logger.error('参数异常检测失败:', error);
  }

  return anomalies;
};

const createAlerts = async (req, res) => {
  try {
    const { recordId, stepIndex, parameters } = req.body;

    const record = await ProductionRecord.findById(recordId);
    if (!record) {
      return res.status(404).json({
        success: false,
        message: '生产记录不存在'
      });
    }

    const anomalies = await detectParameterAnomalies(recordId, stepIndex, parameters);

    if (anomalies.length === 0) {
      return res.json({
        success: true,
        message: '未检测到参数异常',
        data: { alerts: [], count: 0 }
      });
    }

    const alerts = [];
    for (const anomaly of anomalies) {
      const alert = new ParameterAlert({
        ...anomaly,
        productionRecordId: recordId,
        batchId: record.batchId,
        propSerialNumber: record.propSerialNumber,
        stepName: record.steps[stepIndex]?.stepName || `步骤 ${stepIndex + 1}`,
        stepIndex,
        operator: req.user?.id,
        isAutoGenerated: true
      });

      await alert.save();
      alerts.push(alert);
    }

    logger.info(`检测到 ${alerts.length} 个参数异常`, {
      recordId,
      stepIndex,
      alertCodes: alerts.map(a => a.alertCode)
    });

    res.status(201).json({
      success: true,
      message: `检测到 ${alerts.length} 个参数异常`,
      data: { alerts, count: alerts.length }
    });
  } catch (error) {
    logger.error('创建预警失败:', error);
    res.status(500).json({
      success: false,
      message: '创建预警失败',
      error: error.message
    });
  }
};

const getAlerts = async (req, res) => {
  try {
    const {
      recordId,
      batchId,
      status,
      severity,
      alertType,
      startDate,
      endDate,
      page = 1,
      limit = 20
    } = req.query;

    const query = {};

    if (recordId) query.productionRecordId = recordId;
    if (batchId) query.batchId = batchId;
    if (status) query.status = status;
    if (severity) query.severity = severity;
    if (alertType) query.alertType = alertType;

    if (startDate || endDate) {
      query.createdAt = {};
      if (startDate) query.createdAt.$gte = new Date(startDate);
      if (endDate) query.createdAt.$lte = new Date(endDate);
    }

    const alerts = await ParameterAlert.find(query)
      .sort({ createdAt: -1, severity: -1 })
      .limit(limit * 1)
      .skip((page - 1) * limit);

    const total = await ParameterAlert.countDocuments(query);

    const stats = await ParameterAlert.aggregate([
      { $match: query },
      {
        $group: {
          _id: '$status',
          count: { $sum: 1 }
        }
      }
    ]);

    const severityStats = await ParameterAlert.aggregate([
      { $match: { status: { $ne: 'resolved' } } },
      {
        $group: {
          _id: '$severity',
          count: { $sum: 1 }
        }
      }
    ]);

    res.json({
      success: true,
      data: {
        alerts,
        pagination: {
          total,
          page: parseInt(page),
          pages: Math.ceil(total / limit)
        },
        stats: {
          byStatus: stats,
          bySeverity: severityStats
        }
      }
    });
  } catch (error) {
    logger.error('获取预警列表失败:', error);
    res.status(500).json({
      success: false,
      message: '获取预警列表失败',
      error: error.message
    });
  }
};

const getAlertById = async (req, res) => {
  try {
    const alert = await ParameterAlert.findById(req.params.id);

    if (!alert) {
      return res.status(404).json({
        success: false,
        message: '预警记录不存在'
      });
    }

    res.json({
      success: true,
      data: { alert }
    });
  } catch (error) {
    logger.error('获取预警详情失败:', error);
    res.status(500).json({
      success: false,
      message: '获取预警详情失败',
      error: error.message
    });
  }
};

const acknowledgeAlert = async (req, res) => {
  try {
    const { alertId, notes } = req.body;

    const alert = await ParameterAlert.findById(alertId);
    if (!alert) {
      return res.status(404).json({
        success: false,
        message: '预警记录不存在'
      });
    }

    alert.status = 'acknowledged';
    alert.acknowledgedBy = req.user.id;
    alert.acknowledgedAt = new Date();

    if (notes) {
      alert.actions.push({
        action: 'acknowledged',
        performedBy: req.user.id,
        notes
      });
    }

    await retryOperation(() => alert.save(), 3, 500);

    logger.info('预警已确认', { alertId, userId: req.user.id });

    res.json({
      success: true,
      message: '预警已确认',
      data: { alert }
    });
  } catch (error) {
    logger.error('确认预警失败:', error);
    res.status(500).json({
      success: false,
      message: '确认预警失败',
      error: error.message
    });
  }
};

const resolveAlert = async (req, res) => {
  try {
    const { alertId, resolutionNotes } = req.body;

    const alert = await ParameterAlert.findById(alertId);
    if (!alert) {
      return res.status(404).json({
        success: false,
        message: '预警记录不存在'
      });
    }

    alert.status = 'resolved';
    alert.resolvedBy = req.user.id;
    alert.resolvedAt = new Date();
    alert.resolutionNotes = resolutionNotes;

    alert.actions.push({
      action: 'resolved',
      performedBy: req.user.id,
      notes: resolutionNotes
    });

    await retryOperation(() => alert.save(), 3, 500);

    logger.info('预警已解决', { alertId, userId: req.user.id });

    res.json({
      success: true,
      message: '预警已解决',
      data: { alert }
    });
  } catch (error) {
    logger.error('解决预警失败:', error);
    res.status(500).json({
      success: false,
      message: '解决预警失败',
      error: error.message
    });
  }
};

const ignoreAlert = async (req, res) => {
  try {
    const { alertId, reason } = req.body;

    const alert = await ParameterAlert.findById(alertId);
    if (!alert) {
      return res.status(404).json({
        success: false,
        message: '预警记录不存在'
      });
    }

    alert.status = 'ignored';
    alert.actions.push({
      action: 'ignored',
      performedBy: req.user.id,
      notes: reason
    });

    await retryOperation(() => alert.save(), 3, 500);

    logger.info('预警已忽略', { alertId, userId: req.user.id });

    res.json({
      success: true,
      message: '预警已忽略',
      data: { alert }
    });
  } catch (error) {
    logger.error('忽略预警失败:', error);
    res.status(500).json({
      success: false,
      message: '忽略预警失败',
      error: error.message
    });
  }
};

const getAlertSummary = async (req, res) => {
  try {
    const { timeRange = '24h' } = req.query;

    let dateFilter = {};
    const now = new Date();

    switch (timeRange) {
      case '24h':
        dateFilter = { createdAt: { $gte: new Date(now.getTime() - 24 * 60 * 60 * 1000) } };
        break;
      case '7d':
        dateFilter = { createdAt: { $gte: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000) } };
        break;
      case '30d':
        dateFilter = { createdAt: { $gte: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000) } };
        break;
    }

    const [overallStats, byType, bySeverity, trend] = await Promise.all([
      ParameterAlert.aggregate([
        { $match: dateFilter },
        {
          $group: {
            _id: null,
            total: { $sum: 1 },
            pending: { $sum: { $cond: [{ $eq: ['$status', 'pending'] }, 1, 0] } },
            acknowledged: { $sum: { $cond: [{ $eq: ['$status', 'acknowledged'] }, 1, 0] } },
            resolved: { $sum: { $cond: [{ $eq: ['$status', 'resolved'] }, 1, 0] } }
          }
        }
      ]),

      ParameterAlert.aggregate([
        { $match: dateFilter },
        {
          $group: {
            _id: '$alertType',
            count: { $sum: 1 }
          }
        }
      ]),

      ParameterAlert.aggregate([
        { $match: { ...dateFilter, status: { $in: ['pending', 'acknowledged'] } } },
        {
          $group: {
            _id: '$severity',
            count: { $sum: 1 }
          }
        }
      ]),

      ParameterAlert.aggregate([
        { $match: dateFilter },
        {
          $group: {
            _id: { $dateToString: { format: '%Y-%m-%d', date: '$createdAt' } },
            count: { $sum: 1 },
            critical: { $sum: { $cond: [{ $eq: ['$severity', 'critical'] }, 1, 0] } },
            high: { $sum: { $cond: [{ $eq: ['$severity', 'high'] }, 1, 0] } }
          }
        },
        { $sort: { _id: 1 } },
        { $limit: 14 }
      ])
    ]);

    res.json({
      success: true,
      data: {
        summary: overallStats[0] || { total: 0, pending: 0, acknowledged: 0, resolved: 0 },
        byType,
        bySeverity,
        trend,
        timeRange
      }
    });
  } catch (error) {
    logger.error('获取预警摘要失败:', error);
    res.status(500).json({
      success: false,
      message: '获取预警摘要失败',
      error: error.message
    });
  }
};

const createManualAlert = async (req, res) => {
  try {
    const {
      recordId,
      stepIndex,
      parameterName,
      parameterValue,
      alertType,
      severity,
      description
    } = req.body;

    const record = await ProductionRecord.findById(recordId);
    if (!record) {
      return res.status(404).json({
        success: false,
        message: '生产记录不存在'
      });
    }

    const alert = new ParameterAlert({
      productionRecordId: recordId,
      batchId: record.batchId,
      propSerialNumber: record.propSerialNumber,
      stepName: record.steps[stepIndex]?.stepName || `步骤 ${stepIndex + 1}`,
      stepIndex,
      parameterName,
      parameterValue,
      alertType,
      severity: severity || 'medium',
      description,
      operator: req.user.id,
      isAutoGenerated: false
    });

    await retryOperation(() => alert.save(), 3, 500);

    logger.info('手动创建预警', { alertCode: alert.alertCode, userId: req.user.id });

    res.status(201).json({
      success: true,
      message: '手动预警创建成功',
      data: { alert }
    });
  } catch (error) {
    logger.error('创建手动预警失败:', error);
    res.status(500).json({
      success: false,
      message: '创建手动预警失败',
      error: error.message
    });
  }
};

module.exports = {
  createAlerts,
  getAlerts,
  getAlertById,
  acknowledgeAlert,
  resolveAlert,
  ignoreAlert,
  getAlertSummary,
  createManualAlert,
  detectParameterAnomalies
};
