server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: equipment-service
          uri: lb://equipment-service
          predicates:
            - Path=/api/equipment/**
        - id: archive-service
          uri: lb://archive-service
          predicates:
            - Path=/api/archive/**
        - id: restoration-service
          uri: lb://restoration-service
          predicates:
            - Path=/api/restoration/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
