const mongoose = require('mongoose');
const { getConnection } = require('../../config/databases');

const parameterAlertSchema = new mongoose.Schema({
  alertCode: {
    type: String,
    required: true,
    unique: true,
    index: true
  },
  productionRecordId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'ProductionRecord',
    required: true,
    index: true
  },
  batchId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Batch',
    index: true
  },
  propSerialNumber: {
    type: String,
    required: true,
    index: true
  },
  stepName: {
    type: String,
    required: true
  },
  stepIndex: {
    type: Number,
    required: true
  },
  parameterName: {
    type: String,
    required: true
  },
  parameterValue: {
    type: mongoose.Schema.Types.Mixed,
    required: true
  },
  expectedValue: {
    type: mongoose.Schema.Types.Mixed
  },
  minValue: {
    type: Number
  },
  maxValue: {
    type: Number
  },
  unit: {
    type: String
  },
  alertType: {
    type: String,
    enum: ['threshold_exceeded', 'abnormal_value', 'missing_parameter', 'timing_anomaly', 'quality_deviation', 'equipment_fault'],
    required: true
  },
  severity: {
    type: String,
    enum: ['low', 'medium', 'high', 'critical'],
    default: 'medium',
    index: true
  },
  status: {
    type: String,
    enum: ['pending', 'acknowledged', 'resolved', 'ignored'],
    default: 'pending',
    index: true
  },
  deviation: {
    type: Number
  },
  deviationPercent: {
    type: Number
  },
  description: {
    type: String
  },
  operator: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  acknowledgedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  acknowledgedAt: {
    type: Date
  },
  resolvedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  resolvedAt: {
    type: Date
  },
  resolutionNotes: {
    type: String
  },
  actions: [{
    action: String,
    performedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    performedAt: {
      type: Date,
      default: Date.now
    },
    notes: String
  }],
  isAutoGenerated: {
    type: Boolean,
    default: true
  },
  notificationSent: {
    type: Boolean,
    default: false
  },
  notificationChannels: [{
    type: String,
    enum: ['email', 'sms', 'system', 'push']
  }]
}, {
  timestamps: true
});

parameterAlertSchema.index({ status: 1, severity: 1, createdAt: -1 });
parameterAlertSchema.index({ productionRecordId: 1, parameterName: 1 });

parameterAlertSchema.pre('save', function(next) {
  if (!this.alertCode) {
    const timestamp = Date.now().toString().slice(-8);
    const random = Math.floor(Math.random() * 10000).toString().padStart(4, '0');
    this.alertCode = `ALT-${timestamp}-${random}`;
  }
  next();
});

const productionDB = getConnection('productionDB');
module.exports = productionDB.model('ParameterAlert', parameterAlertSchema);
