server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=2
        - id: audit-service
          uri: lb://audit-service
          predicates:
            - Path=/api/audit/**
          filters:
            - StripPrefix=2
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
          filters:
            - StripPrefix=2
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/message/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
